### PR TITLE
DOC - edit readme to import index.js instead of RN module

### PR DESCRIPTION
**Pull request by Fr33maan**
Propose to import the ignite module with crash prevention instead of react-native-i18n module

PS: Sorry, I've not been able to put this file change in my PR with Github GUI.

### CODE REVIEW

**Comment by GantMan** [comment]
Which index.js file are you pointing to in that doc change?

**Comment by GantMan** [comment]
thanks!

**Comment by jamonholmgren** [comment]
@GantMan We should probably release a new version with these changes.

**Comment by GantMan** [comment]
version 1.1.0 released!

**Pull request merged**
