### PR TITLE
upgrade react-native-i18n to latest

### LINKED ISSUE #16: Upgrade to latest i18N
https://github.com/infinitered/ignite/issues/1262

### PR DESCRIPTION
**Pull request by ruddell**
Fix #16

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
LGTM

**Review by kevinvangelder — APPROVED** [review]

**Comment by ruddell** [comment]
This needs a release for users to have the fix when adding to their project

**Comment by kevinvangelder** [comment]
Yep, just haven't had time to do that yet.

**Comment by ruddell** [comment]
@kevinvangelder @jamonholmgren  Can you please release this?  Users are still running into issues because of this module

**Comment by jamonholmgren** [comment]
@ruddell I'm looking at it now, but it appears `yarn test` fails. Looking into it now.

**Comment by jamonholmgren** [comment]
Fixed and published: https://github.com/infinitered/ignite-i18n/releases/tag/v1.2.0

**Comment by jamonholmgren** [comment]
We will be implementing continuous integration and continuous deployment for all Ignite repos soon, @ruddell , so you won't have to wait so long for deployment. @mlaco has been working on it.

**Comment by ruddell** [comment]
Thank you.  I can confirm this fixes the issue with your Andross boilerplate.

**Comment by morgandonze** [comment]
@ruddell I've finished setting up Circle CI here!

**Pull request merged**
